local mod = get_mod("TheyHaveFamilies")

mod.names = {}

local UIFontSettings = require("scripts/managers/ui/ui_font_settings")
local UIWidget = require("scripts/managers/ui/ui_widget")
local template = {}
local size = {
	400,
	1,
}
template.size = size
template.name = "minion_name"
template.unit_node = "j_head"
-- template.unit_node = "root_node"
template.position_offset = {
	0,
	0,
	0.25,
}
template.check_line_of_sight = true
template.max_distance = 7.5
template.screen_clamp = false
template.block_max_distance = false
template.scale_settings = {
	scale_to = 1,
	scale_from = 0.4,
	distance_max = template.max_distance,
	distance_min = 1,
}
template.fade_settings = {
	fade_to = 1,
	fade_from = 0,
	default_fade = 1,
	distance_max = template.max_distance,
	distance_min = template.max_distance - 1 * 2,
	easing_function = math.easeCubic,
}

local header_font_setting_name = "hud_body"
local header_font_settings = UIFontSettings[header_font_setting_name]
template.create_widget_defintion = function(template, scenegraph_id)
	local header_font_color = Color.white(255, true)

	return UIWidget.create_definition({
		{
			style_id = "name",
			pass_type = "text",
			value_id = "name",
			value = "<header_text>",
			style = {
				horizontal_alignment = "center",
				text_vertical_alignment = "center",
				text_horizontal_alignment = "center",
				vertical_alignment = "center",
				offset = {
					0,
					0,
					2,
				},
				font_type = header_font_settings.font_type,
				font_size = header_font_settings.font_size,
				default_font_size = header_font_settings.font_size,
				text_color = header_font_color,
				default_text_color = header_font_color,
				size = size,
			},
		},
	}, scenegraph_id)
end

template.on_enter = function(widget, marker)
	local content = widget.content
	local unit = marker.unit

	content.name = mod.names[unit]
end

template.update_function = function(parent, ui_renderer, widget, marker, template, dt, t)
	local unit = marker.unit
	widget.style.name.font_size = header_font_settings.font_size * marker.scale

	if not HEALTH_ALIVE[unit] then
		marker.remove = true
	end

	local player_manager = Managers.player
	local player = player_manager:local_player(1)
	local player_unit = player.player_unit
	local smart_targeting_extension = ScriptUnit.extension(player_unit, "smart_targeting_system")

	smart_targeting_extension:force_update_smart_tag_targets()
	local targeting_data = smart_targeting_extension:smart_tag_targeting_data()

	local best_unit = ALIVE[targeting_data.unit] and targeting_data.unit

	if unit ~= best_unit then
		marker.draw = false
	end
end

mod:hook_safe("HudElementWorldMarkers", "init", function(self)
	self._marker_templates[template.name] = template
end)

-- NAME GENERATOR --
local function generator_m()
	--NAME
	local name0 = { "", "", "", "" }
	local name00 = { "", "", "", "" }
	local name000 = { "", "", "", "", "", "", "", "" }
	local name00000 = { "", "", "", "", "", "", "", "", "", "", "", "", "" }

	--Generic 1
	local name1 = {
		"B",
		"Bl",
		"Br",
		"C",
		"Ch",
		"Cr",
		"D",
		"Dh",
		"F",
		"Fr",
		"G",
		"Ghr",
		"Gr",
		"Gw",
		"H",
		"J",
		"Jzz",
		"K",
		"Kr",
		"Kyt",
		"L",
		"M",
		"N",
		"P",
		"Ph",
		"Phr",
		"Pl",
		"Qu",
		"Qv",
		"R",
		"Rh",
		"S",
		"Sc",
		"Sh",
		"Sk",
		"Sm",
		"St",
		"Sy",
		"T",
		"Th",
		"Thr",
		"Tr",
		"V",
		"W",
		"Wr",
		"X",
		"Y",
		"Z",
	}
	local name2 = {
		"aag",
		"aal",
		"aan",
		"aarn",
		"ae",
		"aede",
		"aeg",
		"ael",
		"ag",
		"age",
		"ahr",
		"aigg",
		"ail",
		"aile",
		"ainne",
		"ake",
		"akk",
		"al",
		"alk",
		"amne",
		"an",
		"and",
		"ane",
		"ang",
		"ann",
		"ant",
		"ante",
		"antz",
		"anx",
		"anz",
		"ao",
		"ar",
		"arc",
		"ard",
		"ardt",
		"arg",
		"ark",
		"arke",
		"arn",
		"arndt",
		"arpe",
		"arr",
		"arv",
		"arx",
		"as",
		"aul",
		"aulk",
		"aum",
		"auss",
		"awl",
		"ax",
		"axx",
		"aym",
		"ayn",
		"ea",
		"eard",
		"echt",
		"eer",
		"ei",
		"ele",
		"elk",
		"elt",
		"enn",
		"entz",
		"eon",
		"erbe",
		"erg",
		"ess",
		"est",
		"eth",
		"ex",
		"ey",
		"i",
		"iese",
		"ik",
		"im",
		"imm",
		"in",
		"ingh",
		"inkle",
		"irk",
		"ist",
		"iv",
		"ix",
		"o",
		"oadh",
		"obb",
		"odd",
		"ogg",
		"oh",
		"ohl",
		"ohld",
		"oil",
		"ok",
		"oke",
		"okes",
		"ol",
		"olg",
		"oll",
		"onn",
		"oop",
		"or",
		"org",
		"orght",
		"ork",
		"orn",
		"oro",
		"orr",
		"orscht",
		"orst",
		"ort",
		"osch",
		"osk",
		"oth",
		"our",
		"owl",
		"ox",
		"u",
		"udd",
		"udg",
		"ug",
		"uge",
		"ugg",
		"ul",
		"ulfg",
		"ult",
		"un",
		"und",
		"ur",
		"ure",
		"urg",
		"urk",
		"uss",
		"ut",
		"ux",
		"yce",
		"yg",
		"ynes",
		"yre",
		"yrrc",
		"ythe",
	}

	--Generic 2
	local name3 = {
		"Aar",
		"Ab",
		"Abn",
		"Abr",
		"Abs",
		"Ad",
		"Add",
		"Adv",
		"Aeth",
		"Agm",
		"Ak",
		"Alsm",
		"Allocal",
		"Alw",
		"And",
		"Angm",
		"Ansg",
		"Ar",
		"Ard",
		"Arg",
		"Ark",
		"Arkh",
		"Arn",
		"Aubr",
		"Auk",
		"Aurgr",
		"Bal",
		"Balb",
		"Baldr",
		"Ben",
		"Bess",
		"Bil",
		"Bilk",
		"Boult",
		"Burk",
		"Byph",
		"Caid",
		"Cal",
		"Caldr",
		"Call",
		"Cambr",
		"Cant",
		"Car",
		"Carn",
		"Cass",
		"Chaegr",
		"Chal",
		"Char",
		"Cher",
		"Cord",
		"Cort",
		"Cred",
		"Crip",
		"Cum",
		"Cur",
		"Cyk",
		"Cyn",
		"Czev",
		"Dal",
		"Dalm",
		"Dam",
		"Damm",
		"Darg",
		"Dask",
		"Dedd",
		"Deer",
		"Def",
		"Dell",
		"Delph",
		"Dentr",
		"Desv",
		"Dethl",
		"Dev",
		"Dolph",
		"Drac",
		"Drax",
		"Drem",
		"Dress",
		"Drog",
		"Drush",
		"Dur",
		"Eb",
		"Echr",
		"Eg",
		"Eld",
		"En",
		"End",
		"Ephr",
		"Er",
		"Erk",
		"Et",
		"Ezr",
		"Fawr",
		"Fhend",
		"Fir",
		"Fitz",
		"Flamm",
		"Fort",
		"Frenz",
		"Fried",
		"Gai",
		"Gal",
		"Gall",
		"Gamm",
		"Garb",
		"Gargr",
		"Garr",
		"Gast",
		"Gav",
		"Ger",
		"Gid",
		"Girr",
		"Gisb",
		"Glad",
		"Gold",
		"Gorf",
		"Gorm",
		"Gradsh",
		"Grav",
		"Gredd",
		"Grumm",
		"Hag",
		"Hall",
		"Halstr",
		"Hand",
		"Hann",
		"Haph",
		"Hapsh",
		"Harg",
		"Hark",
		"Harr",
		"Harv",
		"Hass",
		"Heir",
		"Held",
		"Herr",
		"Hez",
		"Hick",
		"Hol",
		"Hosk",
		"Hy",
		"Indr",
		"Is",
		"Ishm",
		"Ism",
		"Jac",
		"Jak",
		"Jethr",
		"Joch",
		"Kal",
		"Karb",
		"Karlz",
		"Kart",
		"Keel",
		"Kekr",
		"Kelb",
		"Kelm",
		"Kess",
		"Khark",
		"Khaz",
		"Kilg",
		"Klayd",
		"Klov",
		"Kol",
		"Kor",
		"Kot",
		"Krand",
		"Kratz",
		"Krav",
		"Kreig",
		"Krug",
		"Kryptm",
		"Kub",
		"Kurtz",
		"Kush",
		"Laem",
		"Lak",
		"Lars",
		"Lav",
		"Layr",
		"Lekk",
		"Lenk",
		"Lex",
		"Leyk",
		"Loc",
		"Lom",
		"Lorqu",
		"Lowr",
		"Luk",
		"Lund",
		"Lyk",
		"Lyms",
		"Lyrz",
		"Mab",
		"Magn",
		"Mahl",
		"Mald",
		"Malk",
		"Marb",
		"Marc",
		"March",
		"Markh",
		"Marl",
		"Matth",
		"Max",
		"Meargh",
		"Mill",
		"Mir",
		"Modw",
		"Mord",
		"Munt",
		"Myl",
		"Nath",
		"Neb",
		"Nephth",
		"Ner",
		"Nes",
		"Newm",
		"Nex",
		"Nimr",
		"Nir",
		"Norr",
		"Numth",
		"Nyx",
		"Oct",
		"Ohmn",
		"Omn",
		"Ors",
		"Os",
		"Osm",
		"Oud",
		"Ov",
		"Pan",
		"Parth",
		"Pass",
		"Pax",
		"Phaet",
		"Plisk",
		"Pran",
		"Prax",
		"Pyr",
		"Pyt",
		"Quix",
		"Raiv",
		"Rask",
		"Rat",
		"Rathb",
		"Reik",
		"Rend",
		"Renth",
		"Rest",
		"Reub",
		"Reyl",
		"Reyn",
		"Rhod",
		"Ricc",
		"Rocc",
		"Rol",
		"Ronr",
		"Rork",
		"Rost",
		"Ruthv",
		"Sab",
		"Sam",
		"Sant",
		"Sap",
		"Sarg",
		"Sark",
		"Sas",
		"Scall",
		"Schwarz",
		"Seag",
		"Sem",
		"Seng",
		"Sh",
		"Shor",
		"Shur",
		"Sleev",
		"Son",
		"Sond",
		"Spitz",
		"Stall",
		"Stant",
		"Stark",
		"Strak",
		"Sylv",
		"Tach",
		"Tah",
		"Tall",
		"Tayb",
		"Tel",
		"Terh",
		"Tezl",
		"Thack",
		"Them",
		"Threns",
		"Thyss",
		"Tih",
		"Tilv",
		"Trag",
		"Trant",
		"Traup",
		"Trev",
		"Tsour",
		"Tyr",
		"Uix",
		"Ur",
		"Vaar",
		"Vai",
		"Vak",
		"Val",
		"localn",
		"Vas",
		"Veltr",
		"Verv",
		"Vethr",
		"Vetr",
		"Vett",
		"Vherr",
		"Vianc",
		"Volt",
		"Vor",
		"Vort",
		"Vuyg",
		"Weyldr",
		"Wien",
		"Will",
		"Wols",
		"Xanth",
		"Xix",
		"Zaal",
		"Zab",
		"Zagr",
		"Zar",
		"Zard",
		"Zhok",
		"Zyg",
	}
	local name4 = {
		"a",
		"aac",
		"aan",
		"aard",
		"ack",
		"ael",
		"ah",
		"ahl",
		"ai",
		"aiah",
		"ail",
		"ak",
		"al",
		"alle",
		"am",
		"an",
		"and",
		"ane",
		"ank",
		"ant",
		"anx",
		"aph",
		"ar",
		"ard",
		"ark",
		"arn",
		"arrk",
		"ars",
		"art",
		"as",
		"ash",
		"asz",
		"at",
		"ath",
		"ax",
		"ay",
		"eaux",
		"eb",
		"ec",
		"eck",
		"eg",
		"eiss",
		"ek",
		"el",
		"ell",
		"en",
		"ene",
		"ens",
		"ent",
		"enz",
		"enze",
		"eon",
		"er",
		"ers",
		"es",
		"et",
		"etz",
		"euk",
		"eum",
		"eus",
		"eve",
		"ex",
		"ez",
		"i",
		"ia",
		"iah",
		"ian",
		"ias",
		"ic",
		"id",
		"iel",
		"ien",
		"ik",
		"ike",
		"il",
		"in",
		"ing",
		"iom",
		"ion",
		"ir",
		"is",
		"isch",
		"itz",
		"ium",
		"ius",
		"ix",
		"ize",
		"o",
		"oa",
		"oah",
		"ob",
		"och",
		"ocke",
		"ode",
		"ok",
		"ol",
		"old",
		"ole",
		"olme",
		"olph",
		"om",
		"on",
		"one",
		"ook",
		"ops",
		"or",
		"ore",
		"orn",
		"os",
		"ot",
		"ov",
		"owe",
		"ren",
		"u",
		"uel",
		"ul",
		"ult",
		"um",
		"un",
		"us",
		"use",
		"uul",
		"uv",
		"y",
		"yle",
		"yn",
		"yon",
	}

	--Generic 3
	local name5 = {
		"Abf",
		"Abs",
		"Adr",
		"Ag",
		"Agh",
		"Al",
		"Am",
		"Andr",
		"Ang",
		"Ap",
		"Arct",
		"Arn",
		"Astr",
		"Aug",
		"Balth",
		"Barn",
		"Barr",
		"Barz",
		"Bel",
		"Ben",
		"Blith",
		"Bourg",
		"Cal",
		"Call",
		"Carm",
		"Cart",
		"Cast",
		"Cel",
		"Cons",
		"Cor",
		"Cov",
		"D'anl",
		"Dag",
		"Dann",
		"Del",
		"Dik",
		"Dom",
		"Edm",
		"Eis",
		"End",
		"Er",
		"Gall",
		"Gar",
		"Gid",
		"Gor",
		"Grub",
		"Hall",
		"Hyb",
		"Iakt",
		"Ind",
		"Jer",
		"Kad",
		"Kal",
		"Kan",
		"Kaz",
		"Kharp",
		"Kill",
		"Kluktm",
		"Kur",
		"Kuzm",
		"Kysn",
		"Lar",
		"Lest",
		"Lig",
		"Mal",
		"Mel",
		"Mend",
		"Merr",
		"Mok",
		"Mol",
		"Myct",
		"Nat",
		"Nom",
		"Ob",
		"Ok",
		"Ol",
		"Or",
		"Orch",
		"Querr",
		"Quint",
		"Ram",
		"Rasp",
		"Rass",
		"Rav",
		"Re'hn",
		"Restr",
		"Sab",
		"Sabb",
		"Sak",
		"Salm",
		"Serp",
		"Sev",
		"Sold",
		"Spin",
		"Sur",
		"Suz",
		"Tant",
		"Tell",
		"Thadd",
		"Thass",
		"Tok",
		"Totm",
		"Val",
		"Vald",
		"local",
		"Vask",
		"Ver",
		"Vert",
		"Vil",
		"Vinc",
		"Xanth",
	}
	local name6 = {
		"ab",
		"ac",
		"ach",
		"ad",
		"aed",
		"aen",
		"ag",
		"ais",
		"ak",
		"al",
		"an",
		"and",
		"ant",
		"ar",
		"art",
		"ash",
		"asm",
		"ast",
		"astr",
		"ath",
		"ech",
		"ed",
		"em",
		"en",
		"enh",
		"ens",
		"env",
		"ep",
		"equ",
		"er",
		"erm",
		"ern",
		"es",
		"et",
		"ev",
		"ex",
		"iaf",
		"ic",
		"ig",
		"ik",
		"il",
		"ill",
		"im",
		"in",
		"insk",
		"isp",
		"it",
		"ob",
		"oll",
		"olv",
		"om",
		"on",
		"or",
		"ordn",
		"os",
		"ov",
		"oxt",
		"oz",
		"ul",
		"uld",
		"ur",
		"ust",
		"ut",
		"yak",
		"ym",
		"yps",
		"yr",
	}
	local name7 = {
		"ain",
		"al",
		"an",
		"ant",
		"ar",
		"arn",
		"arr",
		"as",
		"ath",
		"awk",
		"el",
		"en",
		"er",
		"es",
		"ev",
		"iac",
		"ian",
		"ias",
		"ic",
		"ice",
		"iel",
		"in",
		"io",
		"ion",
		"iore",
		"is",
		"ius",
		"o",
		"of",
		"off",
		"on",
		"or",
		"orn",
		"os",
		"ov",
		"u",
		"um",
		"une",
		"us",
		"y",
		"yon",
	}

	--Generic 4
	local name8 = {
		"Abf",
		"Abs",
		"Adr",
		"Ag",
		"Agh",
		"Al",
		"Am",
		"Ang",
		"Ap",
		"Arn",
		"Aug",
		"Bal",
		"Bel",
		"Ben",
		"Cal",
		"Cel",
		"Cor",
		"Cov",
		"Dag",
		"Del",
		"Dik",
		"Dom",
		"Edm",
		"Eis",
		"End",
		"Er",
		"Ess",
		"Gar",
		"Gid",
		"Gor",
		"Hyb",
		"Ind",
		"Jer",
		"Kad",
		"Kal",
		"Kan",
		"Kar",
		"Kaz",
		"Kur",
		"Lar",
		"Lig",
		"Mal",
		"Mel",
		"Mok",
		"Mol",
		"Nat",
		"Nom",
		"Num",
		"Ob",
		"Ok",
		"Ol",
		"Or",
		"Ram",
		"Rav",
		"Sab",
		"Sak",
		"Ser",
		"Sev",
		"Sur",
		"Suz",
		"Tok",
		"Val",
		"local",
		"Ver",
		"Vil",
	}
	local name9 = {
		"ab",
		"ac",
		"ach",
		"ad",
		"aed",
		"aen",
		"ag",
		"ais",
		"ak",
		"al",
		"am",
		"an",
		"and",
		"ant",
		"ar",
		"arof",
		"art",
		"ash",
		"asm",
		"ast",
		"astr",
		"ath",
		"ech",
		"ed",
		"em",
		"en",
		"enh",
		"ens",
		"env",
		"ep",
		"equ",
		"er",
		"erm",
		"ern",
		"es",
		"et",
		"ev",
		"ex",
		"iaf",
		"ic",
		"id",
		"ig",
		"ik",
		"il",
		"ill",
		"im",
		"in",
		"insk",
		"isp",
		"istr",
		"it",
		"ob",
		"oll",
		"olv",
		"om",
		"on",
		"or",
		"ordn",
		"os",
		"ov",
		"oxt",
		"oz",
		"ul",
		"uld",
		"ur",
		"ust",
		"ut",
		"yak",
		"ym",
		"yps",
		"yr",
	}
	local name10 = {
		"ab",
		"ac",
		"ach",
		"ad",
		"aed",
		"aen",
		"ag",
		"ais",
		"ak",
		"al",
		"an",
		"and",
		"ant",
		"ar",
		"arof",
		"art",
		"ash",
		"asm",
		"ast",
		"astr",
		"ath",
		"az",
		"ech",
		"ed",
		"em",
		"en",
		"enh",
		"ens",
		"env",
		"ep",
		"equ",
		"er",
		"erm",
		"ern",
		"es",
		"et",
		"ev",
		"ex",
		"iaf",
		"ic",
		"ig",
		"ik",
		"il",
		"ill",
		"im",
		"in",
		"insk",
		"isp",
		"it",
		"ob",
		"od",
		"oll",
		"olv",
		"om",
		"on",
		"or",
		"ordn",
		"os",
		"ov",
		"oxt",
		"oz",
		"ul",
		"uld",
		"ur",
		"ust",
		"ut",
		"yak",
		"ym",
		"yps",
		"yr",
	}
	local name11 = {
		"al",
		"an",
		"ar",
		"as",
		"el",
		"en",
		"er",
		"es",
		"ev",
		"ic",
		"id",
		"in",
		"io",
		"is",
		"o",
		"of",
		"on",
		"or",
		"os",
		"ov",
		"u",
		"um",
		"us",
		"y",
	}

	--Germanic 1
	local name12 = {
		"Al",
		"Ald",
		"Andhrim",
		"Ant",
		"Ar",
		"As",
		"Bod",
		"Bran",
		"Dur",
		"Fen",
		"Folg",
		"For",
		"Gaud",
		"Ger",
		"Gnaer",
		"God",
		"Gott",
		"Grim",
		"Griv",
		"Gron",
		"Grond",
		"Gun",
		"Gung",
		"Hag",
		"Hal",
		"Half",
		"Heim",
		"Hel",
		"Hen",
		"Horth",
		"Hroth",
		"Ing",
		"Jaeg",
		"Jarl",
		"Jaur",
		"Kjar",
		"Kurg",
		"Leif",
		"Lichten",
		"Loffen",
		"Luf",
		"Lugen",
		"Mag",
		"Meck",
		"Myr",
		"Og",
		"Ol",
		"Orm",
		"Os",
		"Ott",
		"Rag",
		"Rath",
		"Roald",
		"Ryke",
		"Schon",
		"Sig",
		"Skald",
		"Skallag",
		"Skar",
		"Sol",
		"Stef",
		"Stern",
		"Stur",
		"Styr",
		"Sund",
		"Svaf",
		"Sven",
		"Svor",
		"Tannen",
		"Thor",
		"Tor",
		"Ul",
		"Ulf",
		"Ulst",
		"Val",
		"Vraden",
		"Vur",
		"Yme",
		"Yng",
	}
	local name13 = {
		"bald",
		"berg",
		"bjorn",
		"borg",
		"brau",
		"burg",
		"dahl",
		"dall",
		"dor",
		"dr",
		"fast",
		"fels",
		"gar",
		"gard",
		"gelt",
		"gen",
		"ger",
		"gir",
		"grund",
		"gun",
		"hart",
		"heim",
		"helm",
		"hildr",
		"hof",
		"holt",
		"huss",
		"jac",
		"laugur",
		"lin",
		"mag",
		"man",
		"mar",
		"nar",
		"ni",
		"nir",
		"nyr",
		"rag",
		"rand",
		"recht",
		"rek",
		"ric",
		"rich",
		"rid",
		"rik",
		"rim",
		"skald",
		"son",
		"stein",
		"sten",
		"vald",
		"van",
		"local",
		"locall",
		"localr",
		"vek",
		"ven",
		"vendt",
		"vik",
		"vin",
		"vind",
		"vir",
		"wald",
		"win",
	}

	--Germanic 2
	local name14 = { "van", "von", "van der" }
	local name15 = {
		"Bale",
		"Bjorn",
		"Black",
		"Blaze",
		"Bluff",
		"Bolt",
		"Brawn",
		"Cage",
		"Chank",
		"Cowl",
		"Creed",
		"Dahl",
		"Flint",
		"Gar",
		"Gard",
		"Gray",
		"Grim",
		"Grimm",
		"Gritt",
		"Grunt",
		"Grün",
		"Gründ",
		"Guile",
		"Hal",
		"Hank",
		"Hart",
		"Hel",
		"Hildr",
		"Horth",
		"Hroth",
		"Huss",
		"Jarl",
		"Kane",
		"Keel",
		"Kjar",
		"Kronk",
		"Kurg",
		"Lash",
		"Law",
		"Leif",
		"Maul",
		"Meck",
		"Myr",
		"Orm",
		"Pyre",
		"Rath",
		"Rock",
		"Ryke",
		"Schon",
		"Scorn",
		"Shaft",
		"Sharpe",
		"Skald",
		"Skar",
		"Snipe",
		"Sol",
		"Spike",
		"Steel",
		"Stern",
		"Stone",
		"Storm",
		"Strafe",
		"Styr",
		"Sven",
		"Svor",
		"Tannen",
		"Thorn",
		"Tor",
		"Wyld",
	}

	--Middle Eastern 1
	local name19 = { "Al" }
	local name20 = { " ", "-", "'" }
	local name21 = {
		"Abb",
		"Abdo",
		"Ad",
		"Ahm",
		"Akh",
		"Akk",
		"Al",
		"All",
		"An",
		"Anw",
		"Ashr",
		"At",
		"Aw",
		"Aym",
		"Az",
		"Bann",
		"Dak",
		"Dasr",
		"Far",
		"Gam",
		"Haf",
		"Ham",
		"Hamz",
		"Hass",
		"Ism",
		"Jam",
		"Kam",
		"Khal",
		"Mahm",
		"Mokht",
		"Mous",
		"Nab",
		"Nass",
		"Om",
		"Osm",
		"Rah",
		"Rahm",
		"Rash",
		"Sal",
		"Sam",
		"Say",
		"Shaab",
		"Shah",
		"Sub",
		"Tah",
		"Tar",
		"Yous",
	}
	local name22 = {
		"a",
		"aai",
		"ad",
		"af",
		"ah",
		"ail",
		"al",
		"am",
		"an",
		"ar",
		"as",
		"ed",
		"een",
		"ef",
		"eh",
		"ek",
		"el",
		"em",
		"ez",
		"i",
		"id",
		"il",
		"ir",
		"iz",
		"o",
		"oud",
		"ouk",
	}

	--Middle Eastern 2
	local name23 = {
		"Ab",
		"Abd",
		"Ahm",
		"Ailh",
		"Al",
		"Bad",
		"Bay",
		"Ham",
		"Haw",
		"Ibr",
		"Khal",
		"Mak",
		"Most",
		"Muk",
		"Must",
		"Sal",
		"Sharq",
		"Sheh",
		"Sol",
	}
	local name24 = {
		"aal",
		"ad",
		"af",
		"ah",
		"ahy",
		"aij",
		"al",
		"all",
		"am",
		"as",
		"ata",
		"aw",
		"azz",
		"if",
		"im",
		"iy",
		"oum",
		"ull",
	}
	local name25 = { "i", "an", "im", "a", "ah", "id", "em", "at" }

	--Anglo
	local name26 = {
		"Angel",
		"Black",
		"Blister",
		"Blunder",
		"Bone",
		"Candle",
		"Dark",
		"Eagle",
		"Filch",
		"Fyre",
		"Gilden",
		"Gilt",
		"Gospel",
		"Grey",
		"Grim",
		"Gutter",
		"Hammer",
		"Hel",
		"Holy",
		"Hovel",
		"Humble",
		"Iron",
		"Midden",
		"Morte",
		"Muck",
		"Mumble",
		"Noir",
		"Null",
		"Pale",
		"Pender",
		"Pleb",
		"Prayer",
		"Pure",
		"Pyre",
		"Rat",
		"Raven",
		"Retch",
		"Rotten",
		"Sable",
		"Scab",
		"Scrap",
		"Scurry",
		"Shadow",
		"Shamble",
		"Silver",
		"Slop",
		"Slug",
		"Sneer",
		"Snide",
		"Sodden",
		"Spite",
		"Splinter",
		"Stern",
		"Stig",
		"Stink",
		"Terra",
		"Tinker",
		"Totter",
		"Utter",
		"Void",
		"Vull",
		"Winter",
		"Worm",
	}
	local name27 = {
		"bach",
		"bast",
		"blade",
		"blast",
		"blight",
		"bluff",
		"brace",
		"brand",
		"burn",
		"clod",
		"cowl",
		"dung",
		"fall",
		"fast",
		"fax",
		"flame",
		"foot",
		"fort",
		"forth",
		"gard",
		"ghast",
		"gorn",
		"goyle",
		"grim",
		"grub",
		"hame",
		"hart",
		"hawk",
		"heel",
		"hold",
		"hood",
		"hope",
		"hurst",
		"kin",
		"locke",
		"low",
		"man",
		"mar",
		"mark",
		"maul",
		"mere",
		"nesse",
		"pole",
		"rag",
		"scar",
		"scat",
		"shank",
		"soul",
		"staff",
		"stain",
		"stead",
		"stock",
		"stone",
		"strike",
		"sump",
		"swill",
		"toe",
		"tongue",
		"torch",
		"wax",
		"weir",
		"wick",
		"wit",
		"worth",
		"wrath",
	}

	--Title 1
	local name35 = {
		"Abelard",
		"Absalom",
		"Agustius",
		"Alexio",
		"Ambrosius",
		"Antonius",
		"Arkhan",
		"Augustus",
		"Balphus",
		"Borin",
		"Boyle",
		"Caleb",
		"Caspiel",
		"Castinus",
		"Catiel",
		"Clovis",
		"Cornelius",
		"Corvin",
		"Elam",
		"Eli",
		"Elias",
		"Emil",
		"Enos",
		"Erasmus",
		"Faustus",
		"Gad",
		"Galen",
		"Gallianus",
		"Gallius",
		"Gerhart",
		"Gideon",
		"Gisbern",
		"Giselwin",
		"Gregor",
		"Hann",
		"Hans",
		"Hector",
		"Iago",
		"Ignatius",
		"Ishmael",
		"Ivan",
		"Jeremias",
		"Jethro",
		"Jokh",
		"Konrad",
		"Lanto",
		"Luther",
		"Mal",
		"Mattius",
		"Mauger",
		"Merek",
		"Moab",
		"Mordo",
		"Nathaniel",
		"Obed",
		"Octus",
		"Ogg",
		"Orm",
		"Otto",
		"Raphael",
		"Ratibor",
		"Rulf",
		"Seth",
		"Shem",
		"Silas",
		"Solomon",
		"Stavros",
		"Thaddeus",
		"Thane",
		"Titus",
		"Wilk",
		"Xavier",
	}

	-- Random Numbers

	-- Random number to determine name type, don't ask me why they decided to do it this way
	local randomNumber0 = math.ceil(math.random() * #name0)
	local randomNumber00 = math.ceil(math.random() * #name00)
	local randomNumber000 = math.ceil(math.random() * #name000)
	local randomNumber00000 = math.ceil(math.random() * #name00000)

	-- Name Structure

	-- First name
	local firstname = ""
	if randomNumber0 == 1 then
		firstname = name1[math.random(#name1)] .. name2[math.random(#name2)]
	elseif randomNumber0 == 2 then
		firstname = name3[math.random(#name3)] .. name4[math.random(#name4)]
	elseif randomNumber0 == 3 then
		firstname = name5[math.random(#name5)] .. name6[math.random(#name6)] .. name7[math.random(#name7)]
	elseif randomNumber0 == 4 then
		firstname = name35[math.random(#name35)]
	end

	-- Middle eastern name
	local middleeasternname = ""
	if randomNumber00 == 1 then
		middleeasternname = name19[math.random(#name19)]
			.. name20[math.random(#name20)]
			.. name21[math.random(#name21)]
			.. name22[math.random(#name22)]
	elseif randomNumber00 == 2 then
		middleeasternname = name21[math.random(#name21)] .. name22[math.random(#name22)]
	elseif randomNumber00 == 3 then
		middleeasternname = name19[math.random(#name19)]
			.. name20[math.random(#name20)]
			.. name23[math.random(#name23)]
			.. name24[math.random(#name24)]
			.. name25[math.random(#name25)]
	elseif randomNumber00 == 4 then
		middleeasternname = name23[math.random(#name23)] .. name24[math.random(#name24)] .. name25[math.random(#name25)]
	end

	-- German name?
	local weirdname = ""
	if randomNumber00000 == 1 then
		weirdname = name1[math.random(#name1)]
			.. name2[math.random(#name2)]
			.. " "
			.. name8[math.random(#name8)]
			.. name9[math.random(#name9)]
			.. name10[math.random(#name10)]
			.. name11[math.random(#name11)]
	elseif randomNumber00000 == 2 then
		weirdname = name3[math.random(#name3)]
			.. name4[math.random(#name4)]
			.. " "
			.. name8[math.random(#name8)]
			.. name9[math.random(#name9)]
			.. name10[math.random(#name10)]
			.. name11[math.random(#name11)]
	elseif randomNumber00000 == 3 then
		weirdname = name35[math.random(#name35)]
			.. " "
			.. name8[math.random(#name8)]
			.. name9[math.random(#name9)]
			.. name10[math.random(#name10)]
			.. name11[math.random(#name11)]
	elseif randomNumber00000 == 4 then
		weirdname = name8[math.random(#name8)]
			.. name9[math.random(#name9)]
			.. name10[math.random(#name10)]
			.. name11[math.random(#name11)]
			.. " "
			.. name1[math.random(#name1)]
			.. name2[math.random(#name2)]
	elseif randomNumber00000 == 5 then
		weirdname = name8[math.random(#name8)]
			.. name9[math.random(#name9)]
			.. name10[math.random(#name10)]
			.. name11[math.random(#name11)]
			.. " "
			.. name3[math.random(#name3)]
			.. name4[math.random(#name4)]
	elseif randomNumber00000 == 6 then
		weirdname = name1[math.random(#name1)]
			.. name2[math.random(#name2)]
			.. " "
			.. name3[math.random(#name3)]
			.. name4[math.random(#name4)]
	elseif randomNumber00000 == 7 then
		weirdname = name1[math.random(#name1)]
			.. name2[math.random(#name2)]
			.. " "
			.. name5[math.random(#name5)]
			.. name6[math.random(#name6)]
			.. name7[math.random(#name7)]
	elseif randomNumber00000 == 8 then
		weirdname = name3[math.random(#name3)]
			.. name4[math.random(#name4)]
			.. " "
			.. name1[math.random(#name1)]
			.. name2[math.random(#name2)]
	elseif randomNumber00000 == 9 then
		weirdname = name3[math.random(#name3)]
			.. name4[math.random(#name4)]
			.. " "
			.. name5[math.random(#name5)]
			.. name6[math.random(#name6)]
			.. name7[math.random(#name7)]
	elseif randomNumber00000 == 10 then
		weirdname = name5[math.random(#name5)]
			.. name6[math.random(#name6)]
			.. name7[math.random(#name7)]
			.. " "
			.. name1[math.random(#name1)]
			.. name2[math.random(#name2)]
	elseif randomNumber00000 == 11 then
		weirdname = name5[math.random(#name5)]
			.. name6[math.random(#name6)]
			.. name7[math.random(#name7)]
			.. " "
			.. name3[math.random(#name3)]
			.. name4[math.random(#name4)]
	elseif randomNumber00000 == 12 then
		weirdname = name5[math.random(#name5)]
			.. name6[math.random(#name6)]
			.. name7[math.random(#name7)]
			.. " "
			.. name1[math.random(#name1)]
			.. name2[math.random(#name2)]
			.. "-"
			.. name3[math.random(#name3)]
			.. name4[math.random(#name4)]
	elseif randomNumber00000 == 13 then
		weirdname = name5[math.random(#name5)]
			.. name6[math.random(#name6)]
			.. name7[math.random(#name7)]
			.. " "
			.. name3[math.random(#name3)]
			.. name4[math.random(#name4)]
			.. "-"
			.. name1[math.random(#name1)]
			.. name2[math.random(#name2)]
	end

	-- Final name set
	local name = ""
	if randomNumber000 == 1 then
		name = firstname .. " " .. name12[math.random(#name12)] .. name13[math.random(#name13)]
	elseif randomNumber000 == 2 then
		name = firstname .. " " .. name14[math.random(#name14)] .. " " .. name15[math.random(#name15)]
	elseif randomNumber000 == 3 then
		name = firstname .. " " .. middleeasternname
	elseif randomNumber000 == 4 then
		name = firstname .. " " .. name26[math.random(#name26)] .. name27[math.random(#name27)]
	elseif randomNumber000 == 5 then
		name = weirdname
	elseif randomNumber000 == 6 then
		name = name35[math.random(#name35)] .. " " .. name1[math.random(#name1)] .. name2[math.random(#name2)]
	elseif randomNumber000 == 7 then
		name = name35[math.random(#name35)] .. " " .. name3[math.random(#name3)] .. name4[math.random(#name4)]
	elseif randomNumber000 == 8 then
		name = name35[math.random(#name35)]
			.. " "
			.. name5[math.random(#name5)]
			.. name6[math.random(#name6)]
			.. name7[math.random(#name7)]
	end

	return name -- .. ", " .. title;
end

mod:hook_safe("HuskHealthExtension", "init", function(_, _, unit)
	mod.names[unit] = generator_m()

	Managers.event:trigger("add_world_marker_unit", template.name, unit)
end)

mod:hook_safe("HealthExtension", "init", function(_, _, unit)
	mod.names[unit] = generator_m()

	Managers.event:trigger("add_world_marker_unit", template.name, unit)
end)

local AttackSettings = require("scripts/settings/damage/attack_settings")
local attack_results = AttackSettings.attack_results
mod:hook_safe("AttackReportManager", "_process_attack_result", function(_self, buffer_data)
	local attack_result = buffer_data.attack_result
	local attacked_unit = buffer_data.attacked_unit
	local unit_data_extension = ScriptUnit.has_extension(attacked_unit, "unit_data_system")
	local breed_or_nil = unit_data_extension and unit_data_extension:breed()
	local attacking_unit = buffer_data.attacking_unit
	local player_unit_spawn_manager = Managers.state.player_unit_spawn
	local attacking_player = attacking_unit and player_unit_spawn_manager:owner(attacking_unit)

	if attacking_player then
		local tags = breed_or_nil and breed_or_nil.tags
		local allowed_breed = tags and (tags.monster or tags.special or tags.elite)

		if not allowed_breed and attack_result == attack_results.died then
			-- mod:echo("killed " .. mod.names[attacked_unit])
			if not mod.names[attacked_unit] then
				mod.names[attacked_unit] = generator_m()
			end
			Managers.event:trigger("event_combat_feed_kill", attacking_unit, attacked_unit)
		end
	end
end)

mod:hook("HudElementCombatFeed", "_get_unit_presentation_name", function(func, self, unit)
	if mod.names[unit] then
		return mod.names[unit]
	end
	return func(self, unit)
end)

mod:hook_require("scripts/ui/hud/elements/combat_feed/hud_element_combat_feed_settings", function(instance)
	instance.max_messages = 25
end)
