return {
	mod_description = {
		en = "Shows the Steam or Xbox profile picture of each player instead of their character portrait",
		de = "Zeigt statt des Charakterporträts das Steam- oder Xbox-Profilbild jedes Spielers an",
		it = "Mostra l'immagine del profilo Steam o Xbox di ogni giocatore al posto del ritratto del personaggio",
		es = "Muestra la imagen de perfil de Steam o Xbox de cada jugador en lugar del retrato del personaje",
		pl = "Wyświetla zdjęcie profilowe Steam lub Xbox każdego gracza zamiast portretu postaci",
		["pt-br"] = "Exibe a imagem de perfil da Steam ou Xbox de cada jogador no lugar do retrato do personagem",
		ja = "キャラクターのポートレートの代わりに、各プレイヤーのSteamまたはXboxのプロフィール画像を表示します",
		ko = "캐릭터 초상화 대신 각 플레이어의 Steam 또는 Xbox 프로필 사진을 표시합니다",
		["zh-cn"] = "以每位玩家的 Steam 或 Xbox 头像替代角色肖像",
		["zh-tw"] = "以每位玩家的 Steam 或 Xbox 大頭貼取代角色肖像",
		ru = "Показывает изображение профиля Steam или Xbox каждого игрока вместо портрета персонажа",
		fr = "Affiche l'image de profil Steam ou Xbox de chaque joueur à la place du portrait du personnage",
	},
	advanced = {
		en = "Advanced",
		de = "Erweitert",
		it = "Avanzate",
		es = "Avanzado",
		pl = "Zaawansowane",
		["pt-br"] = "Avançado",
		ja = "詳細設定",
		ko = "고급 설정",
		["zh-cn"] = "高级",
		["zh-tw"] = "進階",
		ru = "Дополнительно",
		fr = "Avancé",
	},
	image_proxy_url = {
		en = "Image proxy URL",
		de = "Bildproxy-URL",
		it = "URL del proxy immagini",
		es = "URL del proxy de imágenes",
		pl = "Adres URL serwera proxy obrazów",
		["pt-br"] = "URL do proxy de imagens",
		ja = "画像プロキシのURL",
		ko = "이미지 프록시 URL",
		["zh-cn"] = "图片代理 URL",
		["zh-tw"] = "圖片代理 URL",
		ru = "URL прокси изображений",
		fr = "URL du proxy d'images",
	},
	image_proxy_url_tooltip = {
		en = "Optional. If the game cannot load profile pictures directly, which happens on some Linux/Proton setups, "
			.. "enter the address of your own image proxy here, for example 127.0.0.1:8123. A missing http:// and "
			.. "/avatar?url= are filled in for you. The picture url is appended, percent-encoded. "
			.. "Leave empty to load pictures directly.",
		de = "Optional. Wenn das Spiel Profilbilder nicht direkt laden kann, was bei manchen Linux/Proton-Installationen "
			.. "vorkommt, gib hier die Adresse deines eigenen Bildproxys ein, zum Beispiel 127.0.0.1:8123. Ein fehlendes "
			.. "http:// und /avatar?url= werden für dich ergänzt. Die Bild-URL wird prozentkodiert angehängt. "
			.. "Leer lassen, um Bilder direkt zu laden.",
		it = "Facoltativo. Se il gioco non riesce a caricare direttamente le immagini del profilo, cosa che accade su "
			.. "alcune configurazioni Linux/Proton, inserisci qui l'indirizzo del tuo proxy immagini, ad esempio "
			.. "127.0.0.1:8123. Se mancano, http:// e /avatar?url= vengono aggiunti automaticamente. L'URL "
			.. "dell'immagine viene accodato con codifica percentuale. Lascia vuoto per caricare le immagini direttamente.",
		es = "Opcional. Si el juego no puede cargar las imágenes de perfil directamente, algo que ocurre en algunas "
			.. "configuraciones de Linux/Proton, introduce aquí la dirección de tu propio proxy de imágenes, por ejemplo "
			.. "127.0.0.1:8123. Si faltan, http:// y /avatar?url= se añaden automáticamente. La URL de la imagen se "
			.. "añade al final codificada en porcentaje. Déjalo vacío para cargar las imágenes directamente.",
		pl = "Opcjonalne. Jeśli gra nie może wczytać zdjęć profilowych bezpośrednio, co zdarza się w niektórych "
			.. "konfiguracjach Linux/Proton, wpisz tutaj adres własnego serwera proxy obrazów, na przykład "
			.. "127.0.0.1:8123. Brakujące http:// oraz /avatar?url= zostaną uzupełnione automatycznie. Adres obrazu "
			.. "jest dołączany na końcu i kodowany procentowo. Pozostaw puste, aby wczytywać zdjęcia bezpośrednio.",
		["pt-br"] = "Opcional. Se o jogo não conseguir carregar as imagens de perfil diretamente, o que acontece em "
			.. "algumas configurações Linux/Proton, informe aqui o endereço do seu próprio proxy de imagens, por exemplo "
			.. "127.0.0.1:8123. Se faltarem, http:// e /avatar?url= são preenchidos automaticamente. A URL da imagem é "
			.. "anexada com codificação percentual. Deixe em branco para carregar as imagens diretamente.",
		ja = "任意。一部のLinux/Proton環境のようにゲームがプロフィール画像を直接読み込めない場合は、ここに自分の画像プロキシのアドレスを入力してください（例: 127.0.0.1:8123）。"
			.. "http:// と /avatar?url= が省略されている場合は自動的に補完されます。画像のURLはパーセントエンコードされて末尾に追加されます。空欄にすると画像を直接読み込みます。",
		ko = "선택 사항입니다. 일부 Linux/Proton 환경처럼 게임이 프로필 사진을 직접 불러오지 못하는 경우, 여기에 사용 중인 이미지 프록시 주소를 입력하세요. 예: 127.0.0.1:8123. "
			.. "누락된 http:// 와 /avatar?url= 는 자동으로 채워집니다. 사진 URL은 퍼센트 인코딩되어 뒤에 붙습니다. 비워 두면 사진을 직접 불러옵니다.",
		["zh-cn"] = "可选。如果游戏无法直接加载头像（在部分 Linux/Proton 环境中会出现这种情况），请在此填入你自己的图片代理地址，例如 127.0.0.1:8123。"
			.. "缺少的 http:// 和 /avatar?url= 会自动补全。图片地址会经过百分号编码后附加在末尾。留空则直接加载图片。",
		["zh-tw"] = "選填。如果遊戲無法直接載入大頭貼（在部分 Linux/Proton 環境中會發生），請在此輸入你自己的圖片代理位址，例如 127.0.0.1:8123。"
			.. "缺少的 http:// 與 /avatar?url= 會自動補上。圖片網址會經過百分比編碼後附加在結尾。留空則直接載入圖片。",
		ru = "Необязательно. Если игра не может загрузить изображения профиля напрямую, что случается в некоторых "
			.. "сборках Linux/Proton, укажите здесь адрес своего прокси изображений, например 127.0.0.1:8123. "
			.. "Отсутствующие http:// и /avatar?url= будут подставлены автоматически. Адрес изображения добавляется "
			.. "в конец с процентным кодированием. Оставьте поле пустым, чтобы загружать изображения напрямую.",
		fr = "Facultatif. Si le jeu ne parvient pas à charger les images de profil directement, ce qui arrive sur "
			.. "certaines configurations Linux/Proton, saisissez ici l'adresse de votre propre proxy d'images, par "
			.. "exemple 127.0.0.1:8123. Le http:// et le /avatar?url= manquants sont ajoutés automatiquement. L'URL de "
			.. "l'image est ajoutée à la fin, encodée en pourcentage. Laissez vide pour charger les images directement.",
	},
	image_proxy_url_placeholder = {
		-- A literal address, so it reads the same in every language
		en = "127.0.0.1:8123",
	},
	locations = {
		en = "Show profile pictures in",
		de = "Profilbilder anzeigen in",
		it = "Mostra le immagini del profilo in",
		es = "Mostrar imágenes de perfil en",
		pl = "Pokazuj zdjęcia profilowe w",
		["pt-br"] = "Exibir imagens de perfil em",
		ja = "プロフィール画像を表示する場所",
		ko = "프로필 사진을 표시할 위치",
		["zh-cn"] = "显示头像的位置",
		["zh-tw"] = "顯示大頭貼的位置",
		ru = "Где показывать изображения профиля",
		fr = "Afficher les images de profil dans",
	},
	location_player_hud = {
		en = "Player HUD",
		de = "Spieler-HUD",
		it = "HUD dei giocatori",
		es = "HUD de jugadores",
		pl = "HUD graczy",
		["pt-br"] = "HUD dos jogadores",
		ja = "プレイヤーHUD",
		ko = "플레이어 HUD",
		["zh-cn"] = "玩家 HUD",
		["zh-tw"] = "玩家 HUD",
		ru = "Интерфейс игроков",
		fr = "ATH des joueurs",
	},
	location_player_hud_tooltip = {
		en = "The personal and team player panels, including their Mourningstar variants.",
		de = "Die eigene Spielerleiste und die des Teams, einschließlich ihrer Varianten auf der Mourningstar.",
		it = "Il pannello del giocatore e quelli della squadra, comprese le loro varianti sulla Mourningstar.",
		es = "Los paneles del jugador y del equipo, incluidas sus variantes en la Mourningstar.",
		pl = "Panel własny i panele drużyny, w tym ich warianty na Mourningstar.",
		["pt-br"] = "Os painéis do próprio jogador e da equipe, incluindo suas variantes na Mourningstar.",
		ja = "自分およびチームのプレイヤーパネル（モーニングスター版を含む）。",
		ko = "본인 및 팀원 플레이어 패널(모닝스타 버전 포함).",
		["zh-cn"] = "个人与队伍玩家面板，包括晨星号上的版本。",
		["zh-tw"] = "個人與隊伍玩家面板，包括晨星號上的版本。",
		ru = "Личная панель игрока и панели команды, включая их варианты на «Утренней звезде».",
		fr = "Les panneaux du joueur et de l'équipe, y compris leurs variantes sur le Mourningstar.",
	},
	location_social_menu = {
		en = "Social menu",
		de = "Sozialmenü",
		it = "Menu sociale",
		es = "Menú social",
		pl = "Menu społecznościowe",
		["pt-br"] = "Menu social",
		ja = "ソーシャルメニュー",
		ko = "소셜 메뉴",
		["zh-cn"] = "社交菜单",
		["zh-tw"] = "社交選單",
		ru = "Меню общения",
		fr = "Menu social",
	},
	location_social_menu_tooltip = {
		en = "The player roster, the player plaques and the player popup, including Find Player.",
		de = "Die Spielerliste, die Spielertafeln und das Spieler-Pop-up, einschließlich der Spielersuche.",
		it = "L'elenco dei giocatori, le targhe dei giocatori e il popup del giocatore, inclusa la ricerca giocatore.",
		es = "La lista de jugadores, las placas de jugador y la ventana emergente de jugador, incluida la búsqueda de jugadores.",
		pl = "Lista graczy, tabliczki graczy i okno gracza, w tym wyszukiwanie graczy.",
		["pt-br"] = "A lista de jogadores, as placas de jogador e o pop-up de jogador, incluindo a busca de jogadores.",
		ja = "プレイヤー一覧、プレイヤープレート、およびプレイヤー検索を含むプレイヤーポップアップ。",
		ko = "플레이어 목록, 플레이어 명판, 플레이어 찾기를 포함한 플레이어 팝업.",
		["zh-cn"] = "玩家列表、玩家铭牌以及包含“查找玩家”在内的玩家弹窗。",
		["zh-tw"] = "玩家列表、玩家名牌以及包含「尋找玩家」在內的玩家彈出視窗。",
		ru = "Список игроков, таблички игроков и всплывающее окно игрока, включая поиск игрока.",
		fr = "La liste des joueurs, les plaques de joueur et la fenêtre de joueur, y compris la recherche de joueur.",
	},
	location_lobby = {
		en = "Lobby",
		de = "Lobby",
		it = "Lobby",
		es = "Sala de espera",
		pl = "Poczekalnia",
		["pt-br"] = "Sala de espera",
		ja = "ロビー",
		ko = "로비",
		["zh-cn"] = "大厅",
		["zh-tw"] = "大廳",
		ru = "Лобби",
		fr = "Salon",
	},
	location_lobby_tooltip = {
		en = "The strike team portraits shown while the mission loads.",
		de = "Die Porträts des Einsatzteams, die während des Ladens der Mission angezeigt werden.",
		it = "I ritratti della squadra d'assalto mostrati durante il caricamento della missione.",
		es = "Los retratos del equipo de asalto que se muestran mientras carga la misión.",
		pl = "Portrety drużyny uderzeniowej wyświetlane podczas wczytywania misji.",
		["pt-br"] = "Os retratos do esquadrão exibidos enquanto a missão carrega.",
		ja = "ミッションの読み込み中に表示されるストライクチームのポートレート。",
		ko = "임무를 불러오는 동안 표시되는 특공대 초상화.",
		["zh-cn"] = "任务加载时显示的小队成员肖像。",
		["zh-tw"] = "任務載入時顯示的小隊成員肖像。",
		ru = "Портреты ударной группы, которые показываются во время загрузки задания.",
		fr = "Les portraits de l'équipe d'intervention affichés pendant le chargement de la mission.",
	},
	location_end_screen = {
		en = "End screen",
		de = "Abschlussbildschirm",
		it = "Schermata finale",
		es = "Pantalla final",
		pl = "Ekran końcowy",
		["pt-br"] = "Tela final",
		ja = "リザルト画面",
		ko = "결과 화면",
		["zh-cn"] = "结算界面",
		["zh-tw"] = "結算畫面",
		ru = "Экран завершения",
		fr = "Écran de fin",
	},
	location_end_screen_tooltip = {
		en = "The end of mission summary.",
		de = "Die Missionszusammenfassung am Ende.",
		it = "Il riepilogo di fine missione.",
		es = "El resumen del final de la misión.",
		pl = "Podsumowanie po zakończeniu misji.",
		["pt-br"] = "O resumo ao fim da missão.",
		ja = "ミッション終了時のサマリー画面。",
		ko = "임무 종료 시 표시되는 요약 화면.",
		["zh-cn"] = "任务结束后的总结界面。",
		["zh-tw"] = "任務結束後的總結畫面。",
		ru = "Итоговый экран после завершения задания.",
		fr = "Le récapitulatif de fin de mission.",
	},
	location_party_finder = {
		en = "Party Finder",
		de = "Gruppensuche",
		it = "Cerca gruppo",
		es = "Buscador de grupos",
		pl = "Wyszukiwarka drużyn",
		["pt-br"] = "Busca de grupos",
		ja = "パーティー検索",
		ko = "파티 찾기",
		["zh-cn"] = "队伍查找",
		["zh-tw"] = "隊伍搜尋",
		ru = "Поиск группы",
		fr = "Recherche de groupe",
	},
	location_party_finder_tooltip = {
		en = "Your own party, the listed groups and their join requests.",
		de = "Die eigene Gruppe, die aufgeführten Gruppen und deren Beitrittsanfragen.",
		it = "Il proprio gruppo, i gruppi elencati e le relative richieste di adesione.",
		es = "Tu propio grupo, los grupos de la lista y sus solicitudes de unión.",
		pl = "Własna drużyna, wyświetlone grupy i ich prośby o dołączenie.",
		["pt-br"] = "Seu próprio grupo, os grupos listados e seus pedidos de entrada.",
		ja = "自分のパーティー、掲載されているグループ、およびその参加リクエスト。",
		ko = "자신의 파티, 목록에 표시된 그룹 및 해당 참가 요청.",
		["zh-cn"] = "你自己的队伍、列表中的小队及其加入申请。",
		["zh-tw"] = "你自己的隊伍、列表中的小隊及其加入申請。",
		ru = "Собственная группа, группы в списке и заявки на вступление в них.",
		fr = "Votre propre groupe, les groupes listés et leurs demandes pour les rejoindre.",
	},
	location_inventory = {
		en = "Inventory",
		de = "Inventar",
		it = "Inventario",
		es = "Inventario",
		pl = "Ekwipunek",
		["pt-br"] = "Inventário",
		ja = "インベントリ",
		ko = "소지품",
		["zh-cn"] = "物品栏",
		["zh-tw"] = "物品欄",
		ru = "Инвентарь",
		fr = "Inventaire",
	},
	location_inventory_tooltip = {
		en = "The character portrait in the inventory and character view.",
		de = "Das Charakterporträt in der Inventar- und Charakteransicht.",
		it = "Il ritratto del personaggio nella schermata dell'inventario e del personaggio.",
		es = "El retrato del personaje en la vista de inventario y de personaje.",
		pl = "Portret postaci w widoku ekwipunku i postaci.",
		["pt-br"] = "O retrato do personagem na tela de inventário e de personagem.",
		ja = "インベントリおよびキャラクター画面のキャラクターポートレート。",
		ko = "소지품 및 캐릭터 화면의 캐릭터 초상화.",
		["zh-cn"] = "物品栏与角色界面中的角色肖像。",
		["zh-tw"] = "物品欄與角色畫面中的角色肖像。",
		ru = "Портрет персонажа в окне инвентаря и персонажа.",
		fr = "Le portrait du personnage dans l'inventaire et la vue du personnage.",
	},
}
